// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mobius from "foo/Mobius.res.mjs";
import * as Belt_Array from "@rescript/std/lib/es6/belt_Array.js";

function drawMobius() {
  var points = Belt_Array.make(0, [
        0.0,
        0.0,
        0.0
      ]);
  for(var u = 0; u <= 360; ++u){
    var uRadians = Math.PI * (u / 180.0);
    [
        -1,
        1
      ].forEach((function(uRadians){
        return function (v) {
          points.push(Mobius.pointOnMobius(uRadians, v));
        }
        }(uRadians)));
  }
  Belt_Array.forEach(points, (function (point) {
          console.log({
                x: point[0],
                y: point[1],
                z: point[2]
              });
        }));
}

drawMobius();

export {
  drawMobius ,
}
/*  Not a pure module */
