// Generated by ReScript, PLEASE EDIT WITH CARE


function pointOnMobius(u, v) {
  var x = (1.0 + v / 2.0 * Math.cos(u / 2.0)) * Math.cos(u);
  var y = (1.0 + v / 2.0 * Math.cos(u / 2.0)) * Math.sin(u);
  var z = v / 2.0 * Math.sin(u / 2.0);
  return [
          x,
          y,
          z
        ];
}

export {
  pointOnMobius ,
}
/* No side effect */
