[package]
name = "bukzor_learn_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.86"
cfg-if = "1.0.0"
env_logger = "0.11.5"
log = "0.4.22"
wgpu = "22.1.0"
winit = "0.30.5"
